name: tekartik_jquery
author: alex@tekartik.com
description: jquery for dart
dependencies:
  browser: any
  tekartik_utils:
#    path: ../tekartik_common.dart
    git: https://github.com/alextekartik/tekartik_utils.dart.git
dev_dependencies:
  tekartik_jquery_asset:
#    path: ../tekartik_jquery_asset.dart
    git: https://github.com/alextekartik/tekartik_jquery_asset.dart.git
  