name: tekartik_jquery
version: 0.3.0

description: jquery for dart
publish_to: none
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  collection: '>=1.9.1'
  pub_semver: '>=1.3.0'
  tekartik_jquery_asset:
    git:
      url: git://github.com/tekartik/jquery_asset.dart
      ref: null_safety
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: null_safety
    version: '>=0.6.8'
# dependency_overrides:
#   tekartik_utils:
#     path: ../tekartik_utils.dart
#   tekartik_jquery_asset:
#     path: ../tekartik_jquery_asset.dart
dev_dependencies:
  test: any
  dev_test: '>=0.9.3'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
  build_runner: '>=0.10.1'
  build_test: '>=0.10.3'
  build_web_compilers: '>=0.4.2'