name: tekartik_jquery
version: 0.1.0
author: alex@tekartik.com
description: jquery for dart
dependencies:
  browser: '>=0.10.0'
  collection: '>=1.9.1'
  pub_semver: '>=1.3.0'
  tekartik_jquery_asset:
    git: git://github.com/alextekartik/tekartik_jquery_asset.dart
  tekartik_browser_utils:
    git: git://github.com/tekartik/tekartik_browser_utils.dart
  tekartik_utils:
    git: git://github.com/alextekartik/tekartik_utils.dart
# dependency_overrides:
#   tekartik_utils:
#     path: ../tekartik_utils.dart
#   tekartik_jquery_asset:
#     path: ../tekartik_jquery_asset.dart
dev_dependencies:
  test: any
  dev_test: '>=0.9.3'
