name: tekartik_jquery
version: 0.2.2
author: Alexandre Roux <alex@tekartik.com>
description: jquery for dart
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  browser: '>=0.10.0'
  collection: '>=1.9.1'
  pub_semver: '>=1.3.0'
  tekartik_jquery_asset:
    git:
      url: git://github.com/tekartik/jquery_asset.dart
      ref: dart1
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart1
# dependency_overrides:
#   tekartik_utils:
#     path: ../tekartik_utils.dart
#   tekartik_jquery_asset:
#     path: ../tekartik_jquery_asset.dart
dev_dependencies:
  test: any
  dev_test: '>=0.9.3'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
